spring:
  application:
    name: woowago

server:
  port: 9001

katago:
  path: /katago/squashfs-root/usr/bin/katago
  config: /katago/gtp_config.cfg
  model: /katago/kata1-b18c384nbt-s9996604416-d4316597426.bin